---
- name: install required packages
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - unattended-upgrades

- name: configure unattended-upgrades
  template: src=50unattended-upgrades.j2 dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root mode=0644

- name: enable on unattended-upgrades
  template: src=10periodic.j2 dest=/etc/apt/apt.conf.d/10periodic owner=root group=root mode=0644

- name: reload unattended-upgrades service
  service: name=unattended-upgrades state=restarted

